Repository bellshade/Shell, pull requests merged in 2022-02, with the labels that each got.

#10 feat: menambah materi baru di array
  basic/08_array/README.md
  basic/08_array/array4.sh
Labels: enhancement

#11 fix: Memperbaiki typo dalam Dokumentasi
  README.md
Labels: bug

#13 add: menambah simple project
  simple_project/factorial.sh
  simple_project/prime_checking.sh
Labels: add

#14 add: Materi Shebang
  basic/15_shebang/README.md
  basic/15_shebang/test-shebang-bash.sh
  basic/15_shebang/test-shebang-dash.sh
Labels: add
